# Image URL to use all building/pushing image targets
IMG ?= cloudoperators/ibmcloud-operator

# Run tests
test: 
	mvn compile
	echo "to be done"

# Run locally
run:
	./mvnw compile quarkus:dev: -Ddebug=5006
